# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: William Roger
email: williamroger.frontend@gmail.com
description: "Blog William Roger Desenvolvedor Front-end"
baseurl: "" 
url: "http://williamroger.com.br"
twitter_username: William_Roger
github_username:  WilliamRoger

# Build settings
markdown: kramdown
